n = int(input())
s = input()
if s.count("/") != 1: exit(print("No"))
if s == "/": exit(print("Yes"))
a,b = s.split("/")
if len(a) != len(b): exit(print("No"))
if len(set(a)) != 1 or len(set(b)) != 1: exit(print("No"))
if a[0] != "1" or b[0] != "2": exit(print("No"))
print("Yes")