tc = int(input())
for _ in range(tc):
    slen = int(input())
    s = input()
    s = s.replace("bb", "b.b")
    s = s.replace("cc", "c.c")
    s = s.replace("dd", "d.d")
    s = s.replace("bc", "b.c")
    s = s.replace("cb", "c.b")
    s = s.replace("bd", "b.d")
    s = s.replace("db", "d.b")
    s = s.replace("dc", "d.c")
    s = s.replace("cd", "c.d")
    print(s)
    s = s.replace("baba", "ba.ba")
    s = s.replace("dada", "da.da")
    s = s.replace("caca", "ca.ca")
    s = s.replace("bada", "ba.da")
    s = s.replace("daba", "da.ba")
    s = s.replace("baca", "ba.ca")
    s = s.replace("caba", "ca.ba")
    s = s.replace("cada", "ca.da")
    s = s.replace("daca", "da.ca")

    print(s)
